import requests

import os
from PIL import Image
from IPython.display import IFrame


url='https://www.ibm.com/'
r=requests.get(url)

r.status_code

print(r.request.headers)
print("request body:", r.request.body)
header=r.headers
print(r.headers)


url='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/IDSNlogo.png'
r=requests.get(url)
path=os.path.join(os.getcwd(),'image.png')

with open(path,'wb') as f:
    f.write(r.content)
    
Image.open(path)



# get data from website and insert in Database

from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest' 
#Original Sandbox Environment: 'https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'5000',
  'convert':'USD'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': '0ad53085-1cb2-4eb8-ad9e-3ffbd7e56509',
}

session = Session()
session.headers.update(headers)


try:
  response = session.get(url, params=parameters)
  data = json.loads(response.text)
  #print(data)
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)

import pandas as pd

pd.set_option('display.max_columns', None)

pd.json_normalize(data['data'])

data2 = data[['name', 'symbol', 'slug']].head()

import pyodbc

user = 'DESKTOP-3QJN7S3' + "\)" + "user"  # sql server user name
user_rep = user.replace(")", "")

conn = pyodbc.connect("Driver={SQL Server};"
                          "Server=DESKTOP-3QJN7S3;"  # Server name
                          f"uid={user_rep}"
                          "Database=Data_Model;"  # selected database
                          "Trusted_Connection=yes;")

cursor = conn.cursor()

try:
    conn.execute('''create table Data_Model.dbo.coin_market_data (name varchar(132), symbol varchar(32), slug varchar(32))''')
    conn.commit()
except Exception as e:
    conn.rollback()
    print(f'error{e}')

for index, row in data2.iterrows():
    try:
        conn.execute(
            '''insert into Data_Model.dbo.coin_market_data (name, symbol, slug) values (?, ?, ?) ''', 
            row['name'], row['symbol'], row['slug']
        )
        conn.commit()
    except Exception as e:
        conn.rollback
        print(f'error{e}')
